### PR TITLE
Fix/no guava immutable recipes

### LINKED ISSUE #256: Guava ImmutableMap recipe fails when variable type is ImmutableMap
## What version of OpenRewrite are you using?
I am using:

- OpenRewrite v8.1.8
- Maven plugin v5.2.6
- rewrite-migrate-java v2.0.6

## How are you running OpenRewrite?
I am using the Maven plugin and my project is a single module project.
```xml
<plugin>
    <groupId>org.openrewrite.maven</groupId>
    <artifactId>rewrite-maven-plugin</artifactId>
    <version>5.2.6</version>
    <configuration>
        <checkstyleDetectionEnabled>false</checkstyleDetectionEnabled>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-migrate-java</artifactId>
            <version>2.0.6</version>
        </dependency>
    </dependencies>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
package org.example;

import com.google.common.collect.ImmutableMap;

public class ImmutableCollectionDemo {
    private void poorVariableType() {
        ImmutableMap<String, String> map = ImmutableMap.of("alpha", "beta");
    }
}
```
This code is a little unusual give that the type of `map` is `ImmutableMap`, rather than `Map`.

## What did you expect to see?
```java
package org.example;

import java.util.Map;

public class ImmutableCollectionDemo {
    private void poorVariableType() {
        Map<String, String> map = Map.of("alpha", "beta");
    }
}
```
Both uses of `ImmutableMap` converted for consistency.
(Alternatively, we could play it safe and not change anything in this instance.)

## What did you see instead?
```java
package org.example;

import java.util.Map;

import com.google.common.collect.ImmutableMap;

public class ImmutableCollectionDemo {
    private void poorVariableType() {
        ImmutableMap<String, String> map = Map.of("alpha", "beta");
    }
}
```
Only the second use of `ImmutableMap` is converted leading to a type mis-match and compilation error.

## What is the full stack trace of any errors you encountered?
The generated code does not compile due to the mismatch of types:
```
no instance(s) of type variable(s) K, V exist so that Map<K, V> conforms to ImmutableMap<String, String>
```

## Any other information

I tested the equivalent for `ImmutableList` and `ImmutableSet` and no change to the code was made by either recipe. So perhaps we should be consistent for `ImmutableMap`.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes, if possible. Not sure how useful I'll be as I'm not familiar with your code base, nor have I written my own recipe (yet).

### PR DESCRIPTION
**Pull request by joanvr**
## What's changed?
First, we removed a previous change that allowed Map.of to be assigned to ImmutableMap (this was done to allow nested maps), but was causing uncompilable code.

Added some tests to validate that we do not produce changes in those scenarios for all three collections (List, Set, Map).

Also, since all three recipes (List, Set, Map), have the same duplicated code that needs to be synched, and already had slightly different versions, I've decided to extract it in a parent class, to avoid future inconsistence problems like it was happening right now

## What's your motivation?
Fixes #256 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've added the license header to any new files through `./gradlew licenseFormat`
- [x] I've used the IntelliJ auto-formatter on affected files
- [x] I've updated the documentation (if applicable)

### CODE REVIEW

**Review by timtebeek — APPROVED** [review]
Looks good to me; thanks for fixing the issue and cleaning up the code at the same time.

File: src/main/java/org/openrewrite/java/migrate/guava/AbstractNoGuavaImmutableOf.java [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+import org.openrewrite.java.search.UsesType;
+import org.openrewrite.java.tree.*;
+
+import java.time.Duration;
+import java.util.Objects;
+import java.util.stream.Collectors;
+
+public abstract class AbstractNoGuavaImmutableOf extends Recipe {
+
+    private transient final MethodMatcher IMMUTABLE_MATCHER = new MethodMatcher(getGuavaType() + " of(..)");
```
Comment (timtebeek) [inline src/main/java/org/openrewrite/java/migrate/guava/AbstractNoGuavaImmutableOf.java:36]: What's the background behind adding the `transient` here? Is it because of the call to `getGuavaType` when combined with `final`?

I'm [reading up a bit](https://stackoverflow.com/questions/2968876/final-transient-fields-and-serialization) and found some conflicting reports of using transient, final, and non-trivial objects together when serialization might be involved. 

If you think it'll work fine that fine by me; but wanted to ask both to learn and get a second opinion.

Comment (timtebeek) [reply src/main/java/org/openrewrite/java/migrate/guava/AbstractNoGuavaImmutableOf.java:36]: Maybe it would make sense to define a constructor in `AbstractNoGuavaImmutableOf` that takes in two arguments, and reduce `NoGuavaImmutableMapOf` to just calling that constructor with those two arguments?

Comment (timtebeek) [reply src/main/java/org/openrewrite/java/migrate/guava/AbstractNoGuavaImmutableOf.java]: pushed just now in https://github.com/openrewrite/rewrite-migrate-java/pull/258/commits/20564abd8aba709efd30827c7913abfc218e7b95 
hope you agree; otherwise open for a revert and further discussion

**Review by timtebeek — APPROVED** [review]
