### PR TITLE
Ensure jakarta.annotation dependency is provided scope. Add/change tests

### LINKED ISSUE #728: AddCommonAnnotationsDependencies duplicates dependency when scope is not `compile`
## What version of OpenRewrite are you using?

I am using

- rewrite-migrate-java: 3.10.0-SNAPSHOT

## How are you running OpenRewrite?
I was able to recreate this issue on a smaller scale using the test in [`AddCommonAnnotationsDependenciesTest`](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java)

## What is the smallest, simplest way to reproduce the problem?

In the [`AddCommonAnnotationsDependenciesTest`](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java), add the following into the pom.xml `before`. This seems to work with any scope that is not `compile`.
```xml
<dependencies>
  <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <scope>provided</scope>
      <version>1.3.2</version>
    </dependency>
</dependencies>
```

## What did you expect to see?

Expected just the original dependency to get upgraded to Jakarta.
```xml
<dependency>
	<groupId>jakarta.annotation</groupId>
	<artifactId>jakarta.annotation-api</artifactId>
	<scope>provided</scope>
	<version>1.3.5</version>
</dependency>
```

## What did you see instead?

The original dependency with the non-`compile` scope is upgraded, and also a new duplicate dependency is added without the scope.
```xml
<dependency>
	<groupId>jakarta.annotation</groupId>
	<artifactId>jakarta.annotation-api</artifactId>
	<version>1.3.5</version>
</dependency>
<dependency>
	<groupId>jakarta.annotation</groupId>
	<artifactId>jakarta.annotation-api</artifactId>
	<scope>provided</scope>
 	<version>1.3.5</version>
</dependency>
```

### PR DESCRIPTION
**Pull request by evie-lau**
- Fixes #728 

## What's changed?
Changes recipe that adds `jakarta.annotation-api` to use `provided` scope 

## Anyone you would like to review specifically?
@timtebeek 

## Have you considered any alternatives or workarounds?
Discussed in #728 - considered fixing `AddDependency` or `ChangeDependency`, but may not be the correct solution.

## Any additional context
I believe migrating from Java EE to Jakarta EE, it may be recommended to switch maven dependency scopes to `provided` as the runtime environment likely provides the Jakarta EE APIs. 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

File: src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java [hunk 1]
```diff
@@ -53,7 +53,6 @@ class A {
             //language=xml
             pomXml(
               """
-                <?xml version="1.0" encoding="UTF-8"?>
                 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java:56]:
```suggestion
                <project>
```

File: src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java [hunk 2]
```diff
@@ -62,7 +61,6 @@ class A {
                 </project>
                 """,
               """
-                <?xml version="1.0" encoding="UTF-8"?>
                 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java:64]:
```suggestion
                <project>
```

File: src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java [hunk 3]
```diff
@@ -73,6 +71,62 @@ class A {
...
+                  @Generated("Hello")
+                  class A {
+                  }
+                  """
+              )
+            ),
+            //language=xml
+            pomXml(
+              """
+                <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java:104]:
```suggestion
                <project>
```

File: src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java [hunk 4]
```diff
@@ -73,6 +71,62 @@ class A {
...
+                    <dependency>
+                      <groupId>javax.annotation</groupId>
+                      <artifactId>javax.annotation-api</artifactId>
+                      <version>1.3.2</version>
+                    </dependency>
+                  </dependencies>
+                </project>
+                """,
+              """
+                <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/java/migrate/javax/AddCommonAnnotationsDependenciesTest.java:119]:
```suggestion
                <project>
```

**Review by timtebeek — APPROVED** [review]
Perfect, thanks a lot for the detailed analysis and quick turn around on this!

The comments I placed are nothing to worry about; figured since you had removed the unnecessary `<?xml version="1.0" encoding="UTF-8"?>` already I'd phase out the unnecessary attributes as well to keep the tests free from boilerplate. Definitely not  a reflection on the quality of the work, as that's always 🙌🏻 👏🏻

**Review by timtebeek — APPROVED** [review]
